title: OTT Platforms Portfolio
description: A portfolio showcasing the functionalities, algorithms, and efficiencies of OTT platforms.
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
